### ISSUE TITLE
Releaser - improvements for multiple branches

### ISSUE THREAD

**Issue by grossmannmartin** [shopsys/shopsys#1424]
This issue contains errors and difficulties that occurred during v7.3.2 release and each point should be reconsidered and rejected/resolved.

### What is happening

- [x] `UPGRADE.md` file was not updated with new links to released and next-dev versions (see https://github.com/shopsys/shopsys/blob/v7.3.2/UPGRADE.md).
- [x] When releasing, the initial branch has to be split or the `ReleaseCandidate\CheckPackagesTravisBuildsReleaseWorker` does not check the status of the current state for packages. Master branch is split automatically every time, but the 7.3 branch is not and should be or the user should be instructed to do so.
- [ ] Standards and tests in RC stage failed me on timeout (could be some my configuration)
- [ ] Generated changelog had also the `v8.0.0` section even though all listed PRs there belong to the v 7.3.2 section (see https://github.com/shopsys/shopsys/pull/1413#issuecomment-531942432 and https://github.com/shopsys/shopsys/pull/1413/files#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)
- [x] Update Github URLs so they link to released version and not master. For example code-quality-principles.md links to https://github.com/shopsys/shopsys/tree/master/project-base/src/Resources/definition/product. 
- [ ] Replacing package name in changelog
    - From some point the changelog is always updating packages from `shopsys/shopsys` to `[shopsys/shopsys]` (it applies for all `shopsys/*` packages).
    - It is unwanted as it changes all ocurencies in the file and it is wrong.
- [x] Upgrading to newer version
    - We lack any infromation about upgrading npm package `shopsys/framework` in `packages.json`.
- [x] The best time for creating lock files
    - We should probably generate lock files in `release-candidate` before the applicaation is tested, it may prevent locking some new released pacakage which may caause bug without noticing.
- [x] Commiting symfony.lock files
    - We are missing an instruction for that step.
- [x] List of packages
    - In #1946 we excluded packages which are no longer maintained, but there is a function `get_all_packages` which returns list of packages. This function should be checked and updated if needed.
- [x] `ReleaseCandidate\UpdateChangelogReleaseWorker` says "Please enter no-scope Github token", but no-scope token do not work to me (I created a full-access token in the end)
- [x] #1947 - `AfterRelease\CheckPackagesTravisBuildsReleaseWorker` checks initial branch, but in this stage it should check released version instead.
- [x] Several workers (Travis check, package version check) fails when releasing version in the 7.3 branch. Because package `shopsys/backend-api` does not exist (and never will) in 7.3.x version, nor has the 7.3 branch.
- [x] `AfterRelease\CheckPackagesOnPackagistReleaseWorker` should not check ignored packages (forks). To me, it failed on shopsys/monorepoBuilder and shopsys/ChangelogLinker forks
- [x] **Commit with lock files (composer.lock, package-lock.json, and migrations.lock) was created on the rc-xxx branch and should be directly on an initial branch (master, 7.3, ...)**
- [x] #1946 - `Release\CreateAndPushGitTagsExceptProjectBaseReleaseWorker` do not ignore forks shopsys/monorepoBuilder and shopsys/ChangelogLinker (and should)
- [x] `Release\CheckChangelogForTodaysDateReleaseWorker` updates date and commits changes. Next step is to merge branch. Instruction to push changes is missing and it's really easy to merge branch on GitHub and forget the changed date.
- [x] #1945 - Several workers instruct to split branch with tool `tool-monorepo-split-branch`, but this tool is not working. I used `tool-monorepo-split` for version and `tool-monorepo-force-split-branch` for branch without any problems.
- [x] #1944  - `Release\CreateAndPushGitTagsExceptProjectBaseReleaseWorker` wants username and password because it clones packages with HTTP and as I normally use SSH it was confusing. And it's not clear what user should be used (me or shopsysbot?)

### Expected result
Each point is either rejected or resolved.

**Comment by LukasHeinz** [comment]
This issue is very wide and it is hard to decide what to do with it. Please @grossmannmartin next time try to create issues that have clearer scope. On the other hand I understand that in this case it was tricky.

As the next step I suggest that we go through those items and evaluate if we want to do this. If we want it and it really easy, do it right away. If it's not easy, consider if the effort is worth it (will it speed up release enough) - if it is worthy, create issue or user story with clear scope for each (or group it in some manageable fashion).

**Comment by s3tezsky** [comment]
I am updating information from recent experience of releasing v8.1.0 and v8.1.1.

---

> ReleaseCandidate\UpdateChangelogReleaseWorker says "Please enter no-scope Github token", but no-scope token do not work to me (I created a full-access token in the end)

No-scope token did just fine for me.

---

> Several workers (Travis check, package version check) fails when releasing version in the 7.3 branch. Because package shopsys/backend-api does not exist (and never will) in 7.3.x version, nor has the 7.3 branch.

Same issue is now with shopsys/frontend-api which will exists from version 9

---

> Commit with lock files (composer.lock, package-lock.json, and migrations.lock) was created on the rc-xxx branch and should be directly on an initial branch (master, 7.3, ...)

This seems as a critical issue which can easily break our `tool-monorepo-split`.

---

> Release\CreateAndPushGitTagsExceptProjectBaseReleaseWorker do not ignore forks shopsys/monorepoBuilder and shopsys/ChangelogLinker (and should)

Also it should ignore `shopsys/ordered-form`.

---

>  Release\CreateAndPushGitTagsExceptProjectBaseReleaseWorker wants username and password because it clones packages with HTTP and as I normally use SSH it was confusing. And it's not clear what user should be used (me or shopsysbot?)

This one is really annoying. It cannot be easily workarounded when you are running release from docker container.

You can make it less annoying by overwrite `https://github.com/*` to `http://username@github.com/*` and then only paste the password.

**Comment by s3tezsky** [comment]
Again updating some points which should be improved for future releases.

- [ ] Replacing package name in changelog
    - From some point the changelog is always updating packages from `shopsys/shopsys` to `[shopsys/shopsys]` (it applies for all `shopsys/*` packages).
    - It is unwanted as it changes all ocurencies in the file and it is wrong.
- [ ] Upgrading to newer version
    - We lack any infromation about upgrading npm package `shopsys/framework` in `packages.json`.
- [ ] The best time for creating lock files
    - We should probably generate lock files in `release-candidate` before the applicaation is tested, it may prevent locking some new released pacakage which may caause bug without noticing.
- [ ] Commiting symfony.lock files
    - We are missing an instruction for that step.
- [ ] List of packages
    - In #1946 we excluded packages which are no longer maintained, but there is a function `get_all_packages` which returns list of packages. This function should be checked and updated if needed.
